apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscriptions-database-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscriptions-database
  template:
    metadata:
      labels:
        app: subscriptions-database
    spec:
      containers:
        - name: subscriptions-database
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "admin"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgressubscriptions
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: "subscriptions_db"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: subscriptionsdb
      volumes:
        - name: subscriptionsdb
          persistentVolumeClaim:
            claimName: subscriptions-persistent-volume-claim
---
apiVersion: v1
kind: Service
metadata:
  name: subscriptions-database-cluster-ip
spec:
  type: ClusterIP
  selector:
    app: subscriptions-database
  ports:
    - name: subscriptions-database
      protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: subscriptions-database-load-balancer
spec:
  type: LoadBalancer
  selector:
    app: subscriptions-database
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432