apiVersion: v1
kind: Service
metadata:
  name: collections-node-port
spec:
  type: NodePort
  selector:
    app: collections-service
  ports:
    - name: collections-service
      protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30017