apiVersion: v1
kind: Service
metadata:
  name: tags-database-nodeport
spec:
  type: NodePort
  selector:
    app: tags-database
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30015  # NodePort range is usually 30000-32767
