apiVersion: v1
kind: Service
metadata:
  name: keycloak-service-nodeport
spec:
  type: NodePort
  selector:
    app: keycloak-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30010  # NodePort range is usually 30000-32767
