apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-service
  labels:
    app: keycloak-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-service
  template:
    metadata:
      labels:
        app: keycloak-service
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:26.0.5
          args: [ "start-dev", "--import-realm" ]
          env:
            - name: KEYCLOAK_ADMIN
              value: "admin"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "admin"
            - name: KC_DB
              value: "postgres"
            - name: KC_DB_URL_HOST
              value: "keycloak-database-cluster-ip"
            - name: KC_DB_URL_PORT
              value: "5432"
            - name: KC_DB_URL_DATABASE
              value: "keycloak_db"
            - name: KC_DB_USERNAME
              value: "admin"
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgreskeycloak
                  key: POSTGRES_PASSWORD
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /realms/master
              port: 8080
          volumeMounts:
            - name: realm-config-volume
              mountPath: /opt/keycloak/data/import
              readOnly: true
      volumes:
        - name: realm-config-volume
          configMap:
            name: keycloak-realm-config
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-load-balancer
  labels:
    app: keycloak-service
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: keycloak-service
  type: LoadBalancer