apiVersion: v1
kind: Service
metadata:
  name: auth-database-node-port
spec:
  type: NodePort
  selector:
    app: auth-database
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30021  # NodePort range is usually 30000-32767
