apiVersion: v1
kind: Service
metadata:
  name: reactions-database-nodeport
spec:
  type: NodePort
  selector:
    app: reactions-database
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30026  # NodePort range is usually 30000-32767
