apiVersion: v1
kind: Service
metadata:
  name: seaweed-master-node-port
spec:
  type: NodePort
  selector:
    app: seaweedfs-master
  ports:
    - name: seaweedfs-master
      protocol: TCP
      port: 9333
      targetPort: 9333
      nodePort: 30002
---
apiVersion: v1
kind: Service
metadata:
  name: seaweed-volume-node-port
spec:
  type: NodePort
  selector:
    app: seaweedfs-volume
  ports:
    - name: seaweedfs-volume
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30003
---
apiVersion: v1
kind: Service
metadata:
  name: seaweed-filer-node-port
spec:
  type: NodePort
  selector:
    app: seaweedfs-filer
  ports:
    - name: seaweedfs-filer
      protocol: TCP
      port: 8888
      targetPort: 8888
      nodePort: 30004