---
apiVersion: v1
kind: Service
metadata:
  name: seaweedfs-master
  labels:
    app: seaweedfs-master
spec:
  ports:
    - port: 9333
      targetPort: 9333
      protocol: TCP
      name: master-http
    - port: 19333
      targetPort: 19333
      protocol: TCP
      name: master-grpc
  selector:
    app: seaweedfs-master
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seaweedfs-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seaweedfs-master
  template:
    metadata:
      labels:
        app: seaweedfs-master
    spec:
      containers:
        - name: master
          image: chrislusf/seaweedfs:2.76 # Use a specific stable version
          args:
            - master
            - -ip=seaweedfs-master
            - -port=9333
            - -mdir=/data
            - -port.grpc=19333
          ports:
            - containerPort: 9333
              name: master-http
            - containerPort: 19333
              name: master-grpc
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          volumeMounts:
            - name: master-data
              mountPath: /data
      volumes:
        - name: master-data
          emptyDir: { }
---
apiVersion: v1
kind: Service
metadata:
  name: seaweedfs-volume
  labels:
    app: seaweedfs-volume
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: volume-http
    - port: 18080
      targetPort: 18080
      protocol: TCP
      name: volume-grpc
  selector:
    app: seaweedfs-volume
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seaweedfs-volume
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seaweedfs-volume
  template:
    metadata:
      labels:
        app: seaweedfs-volume
    spec:
      containers:
        - name: volume
          image: chrislusf/seaweedfs:2.76 # Use a specific stable version
          args:
            - volume
            - -port=8080
            - -dir=/data
            - -max=5
            - -ip=$(POD_IP)
            - -mserver=seaweedfs-master:9333
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - containerPort: 8080
              name: volume-http
            - containerPort: 18080
              name: volume-grpc
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "2"
              memory: "2Gi"
          volumeMounts:
            - name: volume-data
              mountPath: /data
      volumes:
        - name: volume-data
          emptyDir: { }
---
apiVersion: v1
kind: Service
metadata:
  name: seaweedfs-filer
  labels:
    app: seaweedfs-filer
spec:
  ports:
    - port: 8888
      targetPort: 8888
      protocol: TCP
      name: filer
  selector:
    app: seaweedfs-filer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seaweedfs-filer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seaweedfs-filer
  template:
    metadata:
      labels:
        app: seaweedfs-filer
    spec:
      containers:
        - name: filer
          image: chrislusf/seaweedfs:2.76 # Use a specific stable version
          args:
            - filer
            - -master=seaweedfs-master:9333
            - -port=8888
          #            - -dir=/data
          ports:
            - containerPort: 8888
              name: filer
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          volumeMounts:
            - name: filer-data
              mountPath: /data
      volumes:
        - name: filer-data
          emptyDir: { }
---
apiVersion: v1
kind: Service
metadata:
  name: seaweedfs-filer
spec:
  type: ClusterIP
  selector:
    app: seaweedfs-filer
  ports:
    - name: seaweedfs-filer
      protocol: TCP
      port: 80
      targetPort: 8888
