apiVersion: v1
kind: Service
metadata:
  name: recipes-node-port
spec:
  type: NodePort
  selector:
    app: recipes-service
  ports:
    - name: recipes-service
      protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30023