apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipes-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recipes-service
  template:
    metadata:
      labels:
        app: recipes-service
    spec:
      containers:
        - name: recipes-service
          image: localhost:9870/kurkle/recipes-service:latest
---
apiVersion: v1
kind: Service
metadata:
  name: recipes-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    app: recipes-service
  ports:
    - name: recipes-service
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: platform-grpc
      protocol: TCP
      port: 666
      targetPort: 666