apiVersion: v1
kind: Service
metadata:
  name: frontend-node-port
spec:
  type: NodePort
  selector:
    app: frontend-service
  ports:
    - name: frontend-service
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001