apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-service
  template:
    metadata:
      labels:
        app: frontend-service
    spec:
      containers:
        - name: frontend-service
          imagePullPolicy: Always
          image: localhost:9870/kurkle/frontend-service:latest
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    app: frontend-service
  ports:
    - name: frontend-service
      protocol: TCP
      port: 80
      targetPort: 80