apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-database-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-database
  template:
    metadata:
      labels:
        app: keycloak-database
    spec:
      containers:
        - name: keycloak-database
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "admin"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgreskeycloak
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: "keycloak_db"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: keycloakdb
      volumes:
        - name: keycloakdb
          persistentVolumeClaim:
            claimName: keycloak-persistent-volume-claim
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-database-cluster-ip
spec:
  type: ClusterIP
  selector:
    app: keycloak-database
  ports:
    - name: keycloak-database
      protocol: TCP
      port: 5432
      targetPort: 5432