apiVersion: v1
kind: Service
metadata:
  name: subscriptions-database-nodeport
spec:
  type: NodePort
  selector:
    app: subscriptions-database
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30007  # NodePort range is usually 30000-32767
