apiVersion: v1
kind: Service
metadata:
  name: collections-database-nodeport
spec:
  type: NodePort
  selector:
    app: collections-database
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30025  # NodePort range is usually 30000-32767
