apiVersion: v1
kind: Service
metadata:
  name: glimpses-node-port
spec:
  type: NodePort
  selector:
    app: glimpses-service
  ports:
    - name: glimpses-service
      protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30016