apiVersion: v1
kind: Service
metadata:
  name: subscriptions-node-port
spec:
  type: NodePort
  selector:
    app: subscriptions-service
  ports:
    - name: subscriptions-service
      protocol: TCP
      port: 80
      targetPort: 80