apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscriptions-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscriptions-service
  template:
    metadata:
      labels:
        app: subscriptions-service
    spec:
      containers:
        - name: subscriptions-service
          image: localhost:9870/kurkle/subscriptions:latest
---
apiVersion: v1
kind: Service
metadata:
  name: subscriptions-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    app: subscriptions-service
  ports:
    - name: subscriptions-service
      protocol: TCP
      port: 80
      targetPort: 80
    - name: plafromgrpc
      protocol: TCP
      port: 666
      targetPort: 666