apiVersion: v1
kind: Service
metadata:
  name: profiles-node-port
spec:
  type: NodePort
  selector:
    app: profiles-service
  ports:
    - name: profiles-service
      protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30012