apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-nodeport
spec:
  type: NodePort
  selector:
    app: elasticsearch-service
  ports:
    - name: elasticsearch-service
      protocol: TCP
      port: 9200
      targetPort: 9200
      nodePort: 30051