apiVersion: v1
kind: Service
metadata:
  name: kibana-nodeport
spec:
  type: NodePort
  selector:
    app: kibana-service
  ports:
    - name: kibana-service
      protocol: TCP
      port: 5601
      targetPort: 5601
      nodePort: 30052