apiVersion: v1
kind: Service
metadata:
  name: glimpses-database-nodeport
spec:
  type: NodePort
  selector:
    app: glimpses-database
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30024  # NodePort range is usually 30000-32767
