apiVersion: apps/v1
kind: Deployment
metadata:
  name: repositories-database-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: repositories-database
  template:
    metadata:
      labels:
        app: repositories-database
    spec:
      containers:
        - name: repositories-database
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "admin"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresrepositories
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: "repositories_db"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: repositoriesdb
      volumes:
        - name: repositoriesdb
          persistentVolumeClaim:
            claimName: repositories-persistent-volume-claim
---
apiVersion: v1
kind: Service
metadata:
  name: repositories-database-cluster-ip
spec:
  type: ClusterIP
  selector:
    app: repositories-database
  ports:
    - name: repositories-database
      protocol: TCP
      port: 5432
      targetPort: 5432