apiVersion: v1
kind: Service
metadata:
  name: reactions-node-port
spec:
  type: NodePort
  selector:
    app: reactions-service
  ports:
    - name: reactions-service
      protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30018