apiVersion: v1
kind: Service
metadata:
  name: tags-node-port
spec:
  type: NodePort
  selector:
    app: tags-service
  ports:
    - name: tags-service
      protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30014