# This is a generated file. Not intended for manual editing.
services:
  profiles:
    build:
      context: "/Users/jeanpaul/Projects/Kurkle/Backend/Solution Items"
      dockerfile: "../Profiles/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Profiles.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "profiles:dev"
    ports: []
    volumes:
    - "/Users/jeanpaul/.nuget/packages:/home/app/.nuget/packages"
    - "/Users/jeanpaul/Projects/Kurkle/Backend/Profiles:/app:rw"
    - "/Users/jeanpaul/Projects/Kurkle/Backend:/src:rw"
    working_dir: "/app"
