apiVersion: v1
kind: Service
metadata:
  name: keycloak-database-nodeport
spec:
  type: NodePort
  selector:
    app: keycloak-database
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30006  # NodePort range is usually 30000-32767
